name: user_repository
description: A Dart package which manages the user domain
publish_to: none 

environment:
  sdk: '^3.2.0'
 
dependencies:
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.8
