name: login_core
description: A dart package that manages the login application layer
publish_to: none

environment:
  sdk: '^3.2.0'

dependencies:
  login_models:
    path: ../login_models
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  meta: ^1.10.0
  freezed: ^2.4.7
  flutter_bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  bloc: ^8.1.3
  uuid: ^4.3.3